#예외처리 예시
#try ~ except ~ finally
try:
        print('Hello')
        print(hello)
except:
        print('error')

#무조건 실행되는 구문
finally:
        print('finish')
